environment:
  matrix:
    - nodejs_version: "7"

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm run release

build: off

matrix:
  fast_finish: true