version: "{build}"

max_jobs: 2

environment:
  matrix:
    - nodejs_version: "7"

platform: x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm run release64
  - dir
  - dir bin
  - 7z a graphiql-ui-win32-x64.zip %APPVEYOR_BUILD_FOLDER%\bin\graphiql-ui-win32-x64

build: off

artifacts:
  - path: graphiql-ui-win32-x64.zip
    name: graphiql-ui-win32-x64

deploy:
  provider: GitHub
  auth_token:
    secure: /9iHt8AO1AhdftYpcP2AVW88/FL1kpc7rsruJV5woXpAkQmAm4pg0eNn5qI3iOk3
  description: ''
  artifact: graphiql-ui-win32-x64.zip
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

matrix:
  fast_finish: true