environment:
  matrix:
    - nodejs_version: "6"

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - node --version
  - npm --version
  - npm run release

matrix:
  fast_finish: true